[package]
name = "test-esp8266_spa-app"
version = "0.0.0"
edition = "2021"

[dev-dependencies]
mock-mainboard-lib = { path = "../mock-mainboard-lib" }
anyhow = "1"
thiserror = "1"
env_logger = "0.10.0"
log = "0.4.17"
assert_cmd = "2.0.8"

[build-dependencies]
cc = "1.0.78"
