pub mod wifi_module_client;
mod handling_error;
mod app_state;
mod wifi_state_machine;
mod discovery_handler;
mod tcp_handler;
mod command;
mod broadcaster;
pub mod advertisement;
pub mod wifi_manager;
mod relay_event;
pub mod view_model;
mod wifi_handler;
