[package]
name = "balboa-spa-messages"
version = "0.1.0"
edition = "2021"

[dependencies]
log = "0.4.17"
anyhow = "1"
num-traits = "0.2.15"
num-derive = "0.3.3"
crc = "3.0.0"
byteorder = "1.4.3"
thiserror = "1"
measurements = "0.11.0"
embedded-hal = "0.2.7"

[dev-dependencies]
env_logger = "0.10.0"