[package]
name = "balboa-spa-messages"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
num-traits = "0.2.15"
num-derive = "0.3.3"
crc = "3.0.0"
byteorder = "1.4.3"
thiserror = "1"
measurements = "0.11.0"
