[package]
name = "wifi-module-lib"
version = "0.0.0"
edition = "2021"

[dependencies]
log = "0.4.17"
anyhow = "1"
thiserror = "1"
balboa-spa-messages = { path = "../balboa-spa-messages" }
common-lib = { path = "../common-lib" }
crossbeam = "0.8.2"

[dev-dependencies]
env_logger = "0.10.0"
